# -*- coding: utf-8 -*-
"""stream app for prej 3.ip

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lIxSnyC5w4oFPnMfnk58fmVSEd7JNl6i
"""

import streamlit as st
import numpy as np
import joblib

model = joblib.load("house_model.pkl")
scaler = joblib.load("scaler.pkl")

st.title("California House Price Prediction 🏠")

MedInc = st.number_input("Median Income")
HouseAge = st.number_input("House Age")
AveRooms = st.number_input("Average Rooms")
AveBedrms = st.number_input("Average Bedrooms")
Population = st.number_input("Population")
AveOccup = st.number_input("Average Occupancy")
Latitude = st.number_input("Latitude")
Longitude = st.number_input("Longitude")

if st.button("Predict Price"):
    input_data = (MedInc, HouseAge, AveRooms, AveBedrms, Population, AveOccup, Latitude, Longitude)
    input_np = np.asarray(input_data).reshape(1, -1)
    input_scaled = scaler.transform(input_np)
    prediction = model.predict(input_scaled)
    st.success(f"🏡 Estimated House Price: ${prediction[0] * 100000:.2f}")
